server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dimai?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

#可不写
  thymeleaf:
    cache: false
    check-template-location: true
    servlet:
      content-type: text/html
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html

  mail:
    host: smtp.qq.com
    username: QQ号码@qq.com
    password: zjyeotrjsjglbahh
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          splitlongparameters=false:

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.aurora.happy.pojo
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.aurora.happy: debug
